### ISSUE TITLE
ThaumCraft 6 dupe pearl

### ISSUE THREAD

**Issue by bigenergy** [Focamacho/DupeFix-Project#1]
Hi, I noticed that you fix dupes in some mods.
If you can, please correct this dupe.
https://github.com/Azanor/thaumcraft-beta/issues/1293

**Comment by Focamacho** [comment]
Thanks for your report/suggestion! I tried to fix the bug and I think I got it, any problems please tell me.

**Comment by bigenergy** [comment]
@Focamacho in EnderIO there is an anvil and it works if you put pearls there (https://ftbwiki.org/Dark_Steel_Anvil)
