### ISSUE TITLE
Mekanism dupe

### ISSUE THREAD

**Issue by bigenergy** [Focamacho/DupeFix-Project#10]
https://github.com/SpongePowered/SpongeForge/issues/3094
Hello, maybe you don’t know how to fix it, but I think you can somehow solve it.
all information is in the link above

**Comment by Focamacho** [comment]
It happens only when SpongeForge is installed?

**Comment by bigenergy** [comment]
@Focamacho This happened with clear forge

I noticed the reason:
When I return to the shipped chunk - the pipes do not have time to connect to each other so quickly and the objects transported by the pipes do not have time to understand that the pipe connection was not successful, since the delay on the server was 45-50ms

**Comment by bigenergy** [comment]
I think this may be due to a slight server delay.
https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/common/tile/transmitter/TileEntityTransmitter.java#L115

**Comment by bigenergy** [comment]
https://github.com/mekanism/Mekanism/issues/5617
The same problem is described here, it seems that the atheists of mekanism are not going to fix it and generally no longer support 1.12.2
