### ISSUE TITLE
Thaumcraft mirror bug

### ISSUE THREAD

**Issue by bigenergy** [Focamacho/DupeFix-Project#11]
1. Take the following items in the hotbar: hand-held magic mirror, magic mirror, any item with NBT data.
2. Place the magic mirror on the block.
3. Connect the hand-held magic mirror to the magic mirror on the unit (RMB)
4. Take a hand-held magic mirror in your left hand, an object with NBT data in your right hand.
5. Click RMB. The GUI of the manual magic mirror will open.
6. Put any item (for example, a normal magic mirror) into the slot of a manual magic mirror
7. An item with NBT data will lose its NBT data.

**Comment by Focamacho** [comment]
Sorry, this mod is only for dupe bugs.
