### ISSUE TITLE
Cyclic Workbench Dupe Glitch

### ISSUE THREAD

**Issue by Velocihater** [Focamacho/DupeFix-Project#12]
https://github.com/Lothrazar/Cyclic/issues/1344

**Comment by Velocihater** [comment]
may be hard to do it without another player, i can record it again if you need it

**Comment by Focamacho** [comment]
Cyclic will probably update soon, but I've made a quick fix to prevent two player from opening the same workbench until it happens.

**Comment by Focamacho** [comment]
DupeFix 1.7 project is available in CurseForge.
https://www.curseforge.com/minecraft/mc-mods/dupefix-project/files/2904387
