### ISSUE TITLE
AstralSorcery dupe

### ISSUE THREAD

**Issue by bigenergy** [Focamacho/DupeFix-Project#13]
https://github.com/HellFirePvP/AstralSorcery/issues/1250

**Comment by Focamacho** [comment]
I can't replicate this bug.
Can you make a video and test the dupe with only Astral Sorcery installed?

**Comment by bigenergy** [comment]
@Focamacho yes, https://youtu.be/cTxjTLrKxcw?t=143

**Comment by Focamacho** [comment]
Fixed in DupeFix Project 1.8
Thanks for the report!

**Comment by Focamacho** [comment]
Thanks for letting me know, I will remove it in the next update.
