### ISSUE TITLE
Interaction dupe between Nether Chest & Satchels/Backpack Mods

### ISSUE THREAD

**Issue by Luke616** [Focamacho/DupeFix-Project#15]
The related issue here:
https://github.com/the-realest-stu/Nether-Chest/issues/8

This becomes a dupe bug when using a backpacks mod such as Satchels. A player can put multiple empty satchels into a Nether Chest, and break it to obtain a stack of Satchels (usually not stack-able). They can then right-click with the stack, place items inside, then un-stack the satchels to duplicate the contents.

Versions used:
Minecraft 1.12.2
Forge 14.23.5.2847
Nether Chest 1.1.1
Vanilla Satchels 1.0.2.4

**Comment by Focamacho** [comment]
Hey, can you test the fix for me?

[mod inside.zip](https://github.com/Focamacho/DupeFix-Project/files/4399038/mod.inside.zip)

**Comment by Luke616** [comment]
Works beautifully! You're a machine, thanks for the quick fix

**Comment by Focamacho** [comment]
Great! I'll upload the new version to CurseForge now.
Thanks for your report!
