### ISSUE TITLE
Effortless building 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Focamacho/DupeFix-Project#2]
If you set your effortless building to place a block down in a none vanilla way and you place a double block like a door and break it while still in place mode it dupes the block.
I will make a video later.

**Comment by Focamacho** [comment]
Please report the bug to them first and send me the link, just like #1

**Comment by P3rf3ctXZer0** [comment]
Its on your end. I will not ask another dev to deal with your issue. As I dealt with devs like Azure before who ignore issues in there code I wish you the best of luck. Ignoring me won't stop the 1.12.2 bug though.
