### ISSUE TITLE
EnderIO Item Frame Dupe Bug

### ISSUE THREAD

**Issue by NordicGamerFE** [Focamacho/DupeFix-Project#20]
If you place Ender IO's dark armor inside of a Item frame all of the upgrades will come off of the piece of armor but still have the upgrades on the armor itself when you take it out of the item frame.

Modpack: MC Eternal 1.3.4

~ xChaosityx

**Comment by Focamacho** [comment]
EnderIO already fixed it in their code, so I think they will update the mod soon. https://github.com/SleepyTrousers/EnderIO/issues/5327
