### ISSUE TITLE
Infinite Ore Doubling

### ISSUE THREAD

**Issue by NordicGamerFE** [Focamacho/DupeFix-Project#21]
When using prospecting from Level Up you receive blocks that cannot be placed. Those blocks can still be placed by a block placer. Tested with Industrial Foregoing block placers and Cyclic item collectors you can just sit there and mine/dupe any ore blocks.

Modpack: MC Eternal 1.3.4

~ reikonyx

**Comment by Focamacho** [comment]
I can't do anything about it because the problem is the oredict used in the Level Up's item, other mods can convert it to a normal ore causing the dupe.
