### ISSUE TITLE
MultiMine

### ISSUE THREAD

**Issue by Hate9** [Focamacho/DupeFix-Project#24]
When using MultiMine in 1.12.2, breaking the bottom of any door drops two of that door (breaking the top only drops one, as normal).
I have no idea what causes this, but it appears to be a known issue.

**Comment by Focamacho** [comment]
Hey, this bug was alreayd reported to MultiMine's github? If yes, can you send here the link to the issue?
If not, can you report it to him first?

**Comment by DonTheBreton** [comment]
Following up for this person: 
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/347

**Comment by focamacho** [comment]
According to this comment, multimine already has a blacklist to avoid this problem.
![image](https://user-images.githubusercontent.com/48870573/93289952-0187b180-f7b6-11ea-9d50-528b754b2fab.png)
