### ISSUE TITLE
Dupe Botania

### ISSUE THREAD

**Issue by TheKlimoT** [Focamacho/DupeFix-Project#25]
https://www.youtube.com/watch?v=KMrFx-ziGQw

**Comment by Focamacho** [comment]
I can't replicate this bug, but I can't understand the language in the video too.
Can you explain it a bit more?
Can you replicate this bug with only Botania installed?

**Comment by TheKlimoT** [comment]
This bug AE2 or Botania. Use Talisman with Botania. and use PatternTerm with AE2. and replicate this bug.

**Comment by focamacho** [comment]
The video is not available anymore and I don't remember how the dupe works
