### ISSUE TITLE
Loot pet duplication bug

### ISSUE THREAD

**Issue by NordicGamerFE** [Focamacho/DupeFix-Project#26]
Hi there!

I've started my own friends MC eternal server recently and was lucky enough to find the "Loot pet" the one that when in hot bar and fed with golden nuggets gives increased drops from mobs and mining.
However the pet also duplicates loot from boss drops (double the same enchant book drop for example). Also when destroying any indrustrial foregoing machine it will duplicate the machine meaning you destroy 1 and get 2 in your inventory.

We've also updated the server to 1.3.51 and the behavior is still the same.

Modpack: MC Eternal 1.3.51

~Proscure

**Comment by Focamacho** [comment]
This bug was already reported to the original mod? If not, please, report it to the author and link the issue here.

**Comment by mxnmnm** [comment]
I remember that and the mod author said it was intentional because that's how he made the pet function so in order to fix it you would probably need to rewrite the entire pet I think.

**Comment by Focamacho** [comment]
I took a look at their github and the mod is not open source, but they have good support so I recommend reporting this bug there.
https://github.com/capnkirok/Inventory-Pets/issues

![image](https://user-images.githubusercontent.com/48870573/79082959-556f0580-7d01-11ea-9ff6-573c1d6d7d1c.png)

**Comment by mxnmnm** [comment]
https://github.com/capnkirok/Inventory-Pets/issues/178

**Comment by mxnmnm** [comment]
I could have sworn he said he wouldn't fix it but I guess I'm thinking of something else maybe lol
