### ISSUE TITLE
Industrial Foregoing Mob Duplicator Dupe

### ISSUE THREAD

**Issue by mxnmnm** [Focamacho/DupeFix-Project#28]
When exact copy is enabled in the configs and a mob like a zombie is holding an item it spawns that exact same zombie with the item.  

Step 1: Get valuable item (ae2 storage cells filled with items would be optimal for max dupe profits)
Step 2: Find a zombie that can pick it up (you might have already gone through and found a zombie that can pick up items and spawned exact copies of that zombies so it would be super ez to do once you found one)
Step 3: Spawn exact copy and kill
Step 4: Profit

I suggest making it so that when exact copy is enabled mobs won't drop the items they are holding.

I am pretty sure they are aware of it considering exact copy is turned off by default and they seem to be done with 1.12 looking at how they have only been focusing on later versions.

**Comment by Focamacho** [comment]
Yeah, I can't do anything about it because this is the function of "exact copy", it copies all the entity data and create a new mob exactly like what was put in the machine.
You can do it with any mob, donkeys will work too.
