### ISSUE TITLE
Flowers disappearing from flower pouch

### ISSUE THREAD

**Issue by EnterFor** [Focamacho/DupeFix-Project#3]
https://github.com/Vazkii/Botania/issues/2709

Hi, I don't know if you play this Mod
So I thought I'd try my luck, this problem has been around for a long time, until now
I wonder if you can fix this error?
I'm Chinese and my English is not good

**Comment by EnterFor** [comment]
Version 1.12.2

**Comment by Focamacho** [comment]
I can't reproduce this bug, do you have a video or tutorial explaining it?

**Comment by EnterFor** [comment]
It seems to only happen on servers.

**Comment by EnterFor** [comment]
I will try to record a video tomorrow. Thank you for your reply

**Comment by EnterFor** [comment]
Hello, here I come. I can't reproduce this error while recording
I found it to be accidental.
If you switch /gamemode 1 you will inevitably reproduce this error
But my players they're all in survival mode, and I'm weird
I don't think this error can be fixed

**Comment by Focamacho** [comment]
Yeah, I have no idea how to fix this since I can't replicate
I'll keep this issue open in case I find a way to replicate and fix the bug
