### ISSUE TITLE
Twilight forest donkey dupe

### ISSUE THREAD

**Issue by bigenergy** [Focamacho/DupeFix-Project#30]
1. Tame a donkey with apples (vanilla)
2. Hang a regular chest on a donkey
3. Open the interface and put in it the charms of inventory and life from the twilight forest
4. Kill the donkey, the contents of the chest will drop out, the donkey will remain alive
5. Hang the chest on the donkey again and get a dup of items

russian video: https://youtu.be/Tldd3RHZPnY?t=116

**Comment by Focamacho** [comment]
Can you test the fix for me? 
[mod inside.zip](https://github.com/Focamacho/DupeFix-Project/files/4519342/mod.inside.zip)

**Comment by bigenergy** [comment]
fixed
