### ISSUE TITLE
Quark minecart dupe

### ISSUE THREAD

**Issue by bigenergy** [Focamacho/DupeFix-Project#31]
Place an empty minecart, take a chest or hopper, click on the minecart with a hopper and click the hopper on the minecart a second time with the shift key held down
This works with all minecarts (for example, it also works with a chest)

https://youtu.be/Tmnfj01HSV4

Fix: `B:"Right click minecarts to add blocks to them"=false` in quark.cfg

**Comment by Focamacho** [comment]
If it can be fixed changing the config file, I think I can't do anything better to fix it.
