### ISSUE TITLE
Roots' Component Pouch dupe bug

### ISSUE THREAD

**Issue by ChromaPIE** [Focamacho/DupeFix-Project#32]
Happens when right-clicking quickly after a Q press. After that the GUI of the pouch would open, all of the contents could be successfully taken out, and the original ones are saved in the thrown one. The Apothecary Pouch may have the same issue, anyway it's not tested.

**Comment by Focamacho** [comment]
Hey, this bug was already reported to Root's github? If yes, can you send here the link to the issue?
If not, can you report it to him first?

**Comment by ChromaPIE** [comment]
Sorry for replying this late. The issue is already sent just now and I'm waiting for their comment. I'll close the issue here as long as the solution came.
