### ISSUE TITLE
Dupe TinkerConstruct

### ISSUE THREAD

**Issue by TheKlimoT** [Focamacho/DupeFix-Project#35]
https://www.youtube.com/watch?v=xGFlKZhSnQI

**Comment by focamacho** [comment]
Tinkers Construct has a blacklist config for it. You can add ``vazkii.botania.common.block.tile.string.TileRedStringContainer`` to prevent this dupe.

![image](https://user-images.githubusercontent.com/48870573/92788262-2cba6d00-f380-11ea-9a38-228c1630fc4b.png)
