### ISSUE TITLE
MEK and AE2

### ISSUE THREAD

**Issue by EnterFor** [Focamacho/DupeFix-Project#4]
1.12.2
Forge:2847
Hello, it's me again, ^_^
I don't know how the words describe this mistake
So I uploaded the video
And I don't know whether this error should be submitted like MEK or AE2
So could you please help me submit it?
Both server and single-player games can reproduce this error

https://youtu.be/GAuielq8F2E

**Comment by EnterFor** [comment]
I used the version
Mekanism-1.12.2-9.8.3.390
appliedenergistics2-rv6-stable-7

**Comment by Focamacho** [comment]
I think the best way to fix this bug and avoid new problems is to remove these recipes.
When possible, can you test this new version of the mod for me?
[DupeFix Project 1.4.zip](https://github.com/Focamacho/DupeFix-Project/files/4134262/DupeFix.Project.1.4.zip)

**Comment by EnterFor** [comment]
I love you dude!!
The test is available
