### ISSUE TITLE
Crash enabling EnderIO Dupe Fix

### ISSUE THREAD

**Issue by Breadabix** [Focamacho/DupeFix-Project#42]
I am using DupeFixProject-1.12.2-3.0, along with EnderIO-1.12.2-5.2.59. When I config the .json to have the enderio dupe fixes enabled the game crashed while loading. 
[crash-2020-09-16_17.42.03-client.txt](https://github.com/Focamacho/DupeFix-Project/files/5233607/crash-2020-09-16_17.42.03-client.txt)

**Comment by focamacho** [comment]
Fixed in version 3.0.1. Thanks for the report.

**Comment by Breadabix** [comment]
Thanks for the quick fix 👍
