### ISSUE TITLE
Dupe bug the farlanders [1.12.2]

### ISSUE THREAD

**Issue by NordicGamerFE** [Focamacho/DupeFix-Project#45]
I reported this issue to the mod creators but was told they wont fix it

I am not quite sure how this bug works but i was told if you wear thorn enchanted armor and let a looter hit you with your hand empty and the weapon on your hot bar it will get copied. Once you kill the looter it will drop your original weapon

**Comment by focamacho** [comment]
Fixed in 3.0.2. Thanks for the report.

**Comment by NordicGamerFE** [comment]
Thank you for your fantastic work 👍
