### ISSUE TITLE
Forestry bags

### ISSUE THREAD

**Issue by X-Niter** [Focamacho/DupeFix-Project#47]
I'm not ![Uploading 94966646...]personally sure how it was done but with forestry bags you can dupe. I have a screenshot I sent and I'm trying to get more info on it. If the screenshot doesn't send please let me know.

**Comment by focamacho** [comment]
Hey, it looks like something went wrong and the image was not sent.

**Comment by X-Niter** [comment]
![image](https://user-images.githubusercontent.com/30506033/95025516-d6271280-064f-11eb-952f-01b21355f146.jpeg)

Okay I hope it sent this time. Working on getting more info from the user. He's been very compliant with wanting to get it fixed as well. Thankfully.

**Comment by X-Niter** [comment]
Okay, the individual is telling me that you drop the bag the same time that you are opening it. He said that it happens client side as well and he has yet to see it fail.

**Comment by focamacho** [comment]
Tell-me if it works
[mod inside.zip](https://github.com/Focamacho/DupeFix-Project/files/5324291/mod.inside.zip)

**Comment by X-Niter** [comment]
Okay, patched was enabled and applied, unfortunately the duplication was still successful.

**Comment by focamacho** [comment]
Oh, it's weird. This worked on my tests :/
No errors in the logs?

**Comment by X-Niter** [comment]
No errors, just the loading initialized from the mod. ![image](https://user-images.githubusercontent.com/30506033/95028091-6753b480-0663-11eb-8d56-147434672e5a.png)

He is going to dig deeper and see if he can manage to collect a in-depth log to find anything from the mod when the action of duping is happening. 
Other then what he can may be able to fined, I'll be home around 2000Hr / 8PM CST and will take the testing to my end as I am more comfortable with your application then my buddy is.

**Comment by focamacho** [comment]
It looks like this log is from the client. DupeFix Project needs to be installed & configured on the server-side.

**Comment by SomeAspy** [comment]
Yes it is client log
(I'm Aspy)

**Comment by X-Niter** [comment]
Ah oops, totally didn't register that this whole time. 
Okay, Welcome aspy <- he was the one testing for me.
I'll be home in a few hours, will run the tests then :) Sorry about that.

**Comment by SomeAspy** [comment]
so will dupefix have to be installed client and server side for this to work, or can the client join without dupefix

**Comment by X-Niter** [comment]
No, it is server side. I just thought it would work client side. My b.

**Comment by focamacho** [comment]
As in my tests everything worked fine, I will close this issue. Any problem let me know.
