### ISSUE TITLE
EnderIO Message

### ISSUE THREAD

**Issue by sejtam-dev** [Focamacho/DupeFix-Project#48]
Hi, I added EnderIO into config, but still get message: `The following mods have their fixies not loaded: EnderIO`. 
I looked at the code and saw that was needed Thaumcraft to enable fixies for EnderIO and remove this message.

**Thx for the repair.**

https://github.com/Focamacho/DupeFix-Project/blob/3.x/src/main/java/com/focamacho/dupefixproject/asm/DupeFixProjectCoreMod.java#L54

Minecraft version: **1.12.2**
Forge version: **forge-14.23.5.2854**
DupeFix version: **3.0.2**

**Comment by focamacho** [comment]
Ah, EnderIO is just required because of a fix for thaumcraft. (https://github.com/Focamacho/DupeFix-Project/issues/1)

I'll fix the message. Thanks for the report.
