### ISSUE TITLE
IC2 and AE2

### ISSUE THREAD

**Issue by EnterFor** [Focamacho/DupeFix-Project#5]
Version: 1.12.2
Forge: 2847

IC2 version: industrialcraft-2-2.8.170-ex112.jar
This error was also found at industrialcraft-2-2.8.188-ex112.jar
Industrialcraft -2-2.8.164-ex112. Jar has no such error

AE2 version: appliedenergy istics2-rv6-stable-7

Error description:
It's my buddy again, Lol. AE2 cannot automatically synthesize items containing Energy Crystal, Lapotron Crystal, re-battery, Generator...Automatic synthesis process stuck.

This problem has existed for a long time, I wonder if you can fix it?

**Comment by Focamacho** [comment]
Does this happen because of the energy stored within these items?

**Comment by EnterFor** [comment]
I think so, but IC2 164 won't cause that problem

**Comment by EnterFor** [comment]
I misunderstood you.
Even if the item does not contain energy, it cannot be automatically synthesized

**Comment by EnterFor** [comment]
Can you test to reproduce the problem?
It would be great to fix this!! ^_^

**Comment by EnterFor** [comment]
Are you still here, buddy?
Are you going to fix this? I'm looking forward to it

**Comment by Focamacho** [comment]
Hey! Sorry for the late reply, I was working on another private project.
I tested the bug and I couldn't understand why this is happening.
The craft work putting the items in a Molecular Assembler but it doesn’t work if crafted using a terminal.
I made a few attempts, but without success to fix it yet.
Have you already reported this to Applied Energistics github? Maybe they help better than me.

**Comment by EnterFor** [comment]
I tried to report to IC, but got no reply.
I will try to report to AE2
Thanks for your reply! ~ ~

**Comment by Focamacho** [comment]
I'm going to close this because I want to keep this mod only with corrections for dupes.
