### ISSUE TITLE
[BUG DUPLICATION] With Piston and JukeBox

### ISSUE THREAD

**Issue by DaDiGui** [Focamacho/DupeFix-Project#52]
I have found this bug by inspecting my 1.12.2 server for possible bugs. The video is in Spanish. But just by watching it you can understand how it works.
[Dupe Bug 1.12.2](https://youtu.be/PI6XUYxB_70)

**Comment by focamacho** [comment]
I'm pretty sure the reason this Dupe doesn't work with optifine is because forge already applies a fix for this bug.
