### ISSUE TITLE
Dupe and mega lag issue

### ISSUE THREAD

**Issue by NordicGamerFE** [Focamacho/DupeFix-Project#56]
The creator just closed the issue with no comment to why he did so what i can assume is either he dont care, or dont work on 1.12.2 anymore. its not really a player done dupe so i dont know if it fits here but it has the ability to make the game unplayable i heard its quite a rare thing but i know it has happend on other modpacks then my own (Ocean Outlast)

https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1792

**Comment by focamacho** [comment]
It looks like he has closed the issue because he already fixed it. (https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/commit/ce5d14fb7e569c2a371e75162e56a2eeb16171f1)
I think he just hasn't updated the mod on curseforge yet.

**Comment by NordicGamerFE** [comment]
Ok good stuff then just hope they push it soon so i dont have raining fish eggs from the sea
