### ISSUE TITLE
Tip on a better way of loading mods' mixins

### ISSUE THREAD

**Issue by Rongmario** [Focamacho/DupeFix-Project#58]
I've seen https://github.com/Focamacho/DupeFix-Project/pull/57, and it's quite nicely done, but, this could fail if a `mcmod.info` isn't found for a mod that is being fixed. And again, it still has the hacky `CoreModManager.getReparseableCoremods().add(jar.getName());` still implemented.

I've made [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter), which is a dynamic way of adding mixins for modded classes via a simple annotation. But it is a dependency and I'm aware that not many devs would like to dependent on another dev's mod. So this is basically a heads up if something like this is desired. If desired, I can open up a PR and implement this. (Basically no larger than a class in footprint).

**Comment by focamacho** [comment]
That looks really great, but as you said, I don't really want to depend on another mod for now.
If something goes wrong with the current method I'll take a better look at MixinBooter.
Thanks for the heads up!
