### ISSUE TITLE
1.12.2 Pam's Harvest craft

### ISSUE THREAD

**Issue by JT122406** [Focamacho/DupeFix-Project#62]
If you craft pams harvest craft water in the crafting table it gives you 8 water for the 1 you put in the table.

**Comment by Ashley123477** [comment]
Pretty sure this isnt a dupe glitch but is intentional for food purposes

**Comment by specklogan** [comment]
This is more for how Pam's food works, but you could easily solve it by changing/removing the recipe in crafttweaker.
