### ISSUE TITLE
Tinkers' Complement Chisel Dupe

### ISSUE THREAD

**Issue by TCreopargh** [Focamacho/DupeFix-Project#63]
How to dupe: make a tinkers' construct chisel with very low durability (for example, make one with paper) then put some blocks into it. When it breaks, the blocks you just put into it will drop, but when you fix it there is another stack of blocks in the chisel.
This mod is wonderful, hope it can get fixed with this mod!

**Comment by focamacho** [comment]
Hello! I think I managed to fix this in version 3.1.1. (https://www.curseforge.com/minecraft/mc-mods/dupefix-project/files/3160314)
Thanks for the report!
