### ISSUE TITLE
Personal Chest from Mekanism Mod

### ISSUE THREAD

**Issue by runescapejon** [Focamacho/DupeFix-Project#68]
Hello, I am running on DupeFix-Project - 3.1.1 my issue happened whenever a user place down their personal chest they cannot open it unless they are holding another personal chest in hand, I'm not too sure as to what is the dupe for this item but it seems tat it's here that contains the issue (link below). Is there a viable alternative solution?  Thank you. 
https://github.com/Focamacho/DupeFix-Project/blob/3.x/src/main/java/com/focamacho/dupefixproject/event/MekanismFixes.java#L32-L33

**Comment by focamacho** [comment]
Oh, thanks for reporting it.
As now we are using mixins for DupeFix Project, I think I can make a better fix for it.
