### ISSUE TITLE
Botania duplication bug report

### ISSUE THREAD

**Issue by runescapejon** [Focamacho/DupeFix-Project#86]
Hello, 
Well first you'll need the following mods
1) botania 
2) Tinkers Construct (or another mod that can link with any chest in it's inventory)

How to reproduce
1) Place a Red Stringed Container
2) Next to a Red String Container, you'll need to place a shulker box 
3) lastly next to Red String Container, you'll need to place a Crafting Station. 
4) Using the wand of Forest to contact the Red String Container to any shulker box (could use any modded ones or vanilla)
5) Using an auto breaker or have another player break the shulker with any items inside while another person is in the crafting station and you'll be able to dupe. I'll try to display screenshots or videos.

Connecting the Shulker box: 
https://gyazo.com/886e502e1cf4b9db590e8072cc7c4b8a

demonstration gif:
https://gyazo.com/886e502e1cf4b9db590e8072cc7c4b8a
As you saw the shulker box that contains the diamond was broken but the crafting station that displays what was in the shulker box able to take the items out of it because of the Red Stringed Container that is used to bind inventory somehow,

More info about Red Stringed Container can be found here for additional information. 

https://ftb.fandom.com/wiki/Red_Stringed_Container

**Comment by focamacho** [comment]
Unfortunately, Crafting Station has a lot of dupes (many machines end up being somewhat "incompatible" with it)
An example is Thermal Expansion's machines, you can use the Crafting Station to change the output slot while processing an item to dupe it.

At least you can blacklist it in Tinkers Construct's config file.
I think the key will be `vazkii.botania.common.block.tile.string.TileRedStringContainer`

**Comment by runescapejon** [comment]
Understandable thank you.
