### ISSUE TITLE
Advanced Solar Panels

### ISSUE THREAD

**Issue by Romz24** [Focamacho/DupeFix-Project#9]
With the help of this mod, I managed to duplicate items, can you fix it?

Mod: https://www.curseforge.com/minecraft/mc-mods/advanced-solar-panels
Video: https://www.youtube.com/watch?&v=dH6CWvQXbQQ

**Comment by Focamacho** [comment]
Oookay, It's very strange.
So it's just a "dupe block"? What the block was supposed to do?

**Comment by Focamacho** [comment]
It seems to be a feature of the mod(idk why the author added it), but It's not really a dupe bug.
Advanced Solar Panels have a config to disable the recipe for the double slab.
