### ISSUE TITLE
Quark Pickarang Dupe Bug

### ISSUE THREAD

**Issue by mxnmnm** [Focamacho/DupeFix-Project#93]
https://github.com/Azanor/thaumcraft-api/issues/66

**Comment by focamacho** [comment]
Do you have any video? I can't replicate this

**Comment by AgentDelta** [comment]
I think it can be seen correctly on [this video](https://mega.nz/file/Z9YXmYLa#CMcqhaFhq8TLkGuDhX3nuFJWSbu57iH6HTfkRzuNstY) I made. You need to throw the pickarang to the chest on the nearest point to the pedestal

**Comment by focamacho** [comment]
Thanks for the video!
Seems it can happen with any block, not only the pedestal. It is a Quark issue, they're not checking if the item entity is "dead" before adding it to the player's inventory, so the item is added twice.

Thanks for the report!
