### ISSUE TITLE
[Incompatibility] Game crashes on load

### ISSUE THREAD

**Issue by Vapaman** [Focamacho/DupeFix-Project#94]
Crash report:
[crash-2021-07-21_00.34.49-client.txt](https://github.com/Focamacho/DupeFix-Project/files/6851371/crash-2021-07-21_00.34.49-client.txt)
The mod worked fine in version 3.1.2 and crash occured when updating to 3.1.3
Mod list
![kuva](https://user-images.githubusercontent.com/77460466/126399585-aed8fb48-d497-4212-8df9-886d106fe016.png)

**Comment by focamacho** [comment]
I think it is a mixin version issue, can you try rename DupeFix Project for it to be the first on the list?
You can also try add [this mod](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility) to your modpack.

**Comment by Vapaman** [comment]
Yup you were right. It works after installing that mixin fix. Should I leave this issue open that other people that have the same issue can find a fix?
