### ISSUE TITLE
Thaumcraft 6 entities can be picked up during their death animation allowing duping of parts

### ISSUE THREAD

**Issue by Vapaman** [Focamacho/DupeFix-Project#95]
To reproduce:
1. Place down any animated construct (golem, bore, crossbow)
2. Kill it and then quickly sneak and interact with it to pick it up during its death animation, the placer item is dropped with the usual drops.

Because most thaumcrafts animated constructs drop usable items, this allows for easy golem part farming/duplication

**Comment by Vapaman** [comment]
I'll put this here if its any use: https://github.com/TheCodex6824/ThaumicAugmentation/issues/214

**Comment by focamacho** [comment]
Thanks for the report!

**Comment by Vapaman** [comment]
Works without issues. Thanks for fixing and for this mod in general!
